pub const DEFAULT_PORT: u16 = 2137;
pub const DEFAULT_SEEK_STEP: i64 = 5;
pub const DEFAULT_VOLUME_STEP: i8 = 5;
pub const DEFAULT_SPEED_STEP: i16 = 5;
pub const DEFAULT_GROUP_BY: [&str; 2] = ["albumartist", "album"];
pub const DEFAULT_CONFIG_DIR: &str = "amusing";
pub const DEFAULT_CONFIG_FILE: &str = "amusing.toml";
pub const DEFAULT_BACKTRACE_FILE: &str = "amusing.backtrace";
pub const UNKNOWN: &str = "<unknown>";
